FROM composer:1.10@sha256:7b75b9b1614cdfa09357a7c62bb2516d3b5ee8418e048376734ea1e19ed0d30f

ARG composer_dev_arg

RUN apk add --no-cache \
    patch

COPY composer.json \
    composer.lock \
    ./

RUN composer --no-interaction install ${composer_dev_arg} --ignore-platform-reqs --no-autoloader --no-suggest --prefer-dist

COPY test/ test/
COPY src/ src/

RUN composer --no-interaction dump-autoload ${composer_dev_arg} --classmap-authoritative
