name: build-and-test
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Compose
        uses: ndeloof/install-compose-action@main
        with:
          legacy: true

      - name: run docker build for test image
        run: make build-test
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        tests: [composer, phpcs, phpunit, behat]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Compose
        uses: ndeloof/install-compose-action@main
        with:
          legacy: true
      - name: test docker image
        run: make test-${{ matrix.tests }}
